wifeName: padhu
spring:
 client:
   serviceUrl:
    defaultZone: http://localhost:/8761/eureka
 cloud:
   stream:
     bindings:
       inventoryQ:
         destination: inventoryQ
       checkinQ:
         destination: checkinQ  

  
