spring:
 rabbitmq:  
   port : 5672
   username: guest
   password: guest
 info: 
    app: 
      name: Boot Actuator
      description: My third round
      version: 1.1.1
 client:
   serviceUrl:
    defaultZone: http://localhost:/8761/eureka
 cloud:
   config
      uri: http://localhost:8888
org:
 pafour: param-padhu-pavalan-parithi
 
