spring:
   client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
zuul:
  routes:
  prefix: /api
    multiplication:
      serviceId: fares-service
      path: /mulitplication/**
    notifications:
      serviceId: notification-service
      path: /notification/**
    fare:
      path: /fare/*
      uri:http://localhost:8080
  endpoints:
     trace:
       sensitive: false
  ribbon:
    eureka:
       enabled: false
